### ISSUE TITLE
Error using QtAwesome 1.2.1 with PySide6-Essentials 6.4.0.1

### ISSUE THREAD

**Issue by TinyMarsh** [spyder-ide/qtawesome#219] opened 2022-10-31 16:13 UTC
#### Description
Running QtAwesome 1.2.1 with PySide6-Essentials 6.4.0.1 gives following Traceback;

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<snip>__main__.py", line 3, in <module>
    from .main.main_window import MainWindow
  File "<snip>main/main_window.py", line 4, in <module>
    import qtawesome as qta
  File "<snip>.venv/lib/python3.8/site-packages/qtawesome/__init__.py", line 23, in <module>
    from qtpy import QtCore, QtWidgets, QtGui
  File "<snip>.venv/lib/python3.8/site-packages/qtpy/QtCore.py", line 116, in <module>
    Qt.MidButton = Qt.MouseButton.MiddleButton = Qt.MiddleButton
  File "/usr/lib/python3.8/enum.py", line 427, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.
```

#### To Reproduce
Running in a venv with PySide6-Essentials-6.4.0.1, shiboken6-6.4.0.1, and QtAwesome1.2.1 packages installed. When `import qtawesome as qta` is included in the project.

**Comment by dalthviz** [comment] 2022-10-31 16:42
Hi @TinyMarsh thank you for the feedback! I think this is a duplicate of https://github.com/spyder-ide/qtawesome/issues/216 and actually a QtPy issue as described at https://github.com/spyder-ide/qtawesome/issues/216#issuecomment-1289108077

Since a couple of these issues have been raised probably we will try to release a new version of QtPy to fix the error with PySide6 6.4 soon :+1:

Let us know if the info above helps!

**Comment by TinyMarsh** [comment] 2022-11-01 11:32
Thanks @dalthviz. Looking forward to the new release! 👍

**Comment by dalthviz** [comment] 2022-12-09 22:04
Closing this since qtpy v2.3.0 is already available

**Closed by dalthviz** 2022-12-09 22:04 UTC
Labels: reso:duplicate, reso:notQtAwesome
