### ISSUE TITLE
memory leak when set spinning animation on icon (qtawesome 2.3.1 ; win11 ; pyside6.4.2)

### ISSUE THREAD

**Issue by iqxd** [spyder-ide/qtawesome#235] opened 2023-05-07 06:51 UTC
a minimal script from example which leak memory :  (qtawesome 2.3.1  ;  windows 11 ; pyside 6.4.2)

```python
from PySide6.QtWidgets import QApplication,QPushButton
import qtawesome as qta

app = QApplication([])
spin_button = QPushButton('Spinning icon')
spin_icon = qta.icon('fa5s.spinner', color='red',
                     animation=qta.Spin(spin_button))
spin_button.setIcon(spin_icon)
spin_button.show()

app.exec()
```

**Comment by dalthviz** [comment] 2023-05-16 22:00
Hi @iqxd thank you for the feedback! Could this be related with https://github.com/spyder-ide/qtawesome/issues/223? Checking, I was able to reproduce this with PySide6 6.4.2 but seems like the leak has less impact if you use PySide6 6.4.3 and seems like there is no leak if you use PySide6 6.5.0 🤔 

Could it be possible for you to update to PySide6 6.5.0 and see if that helps? 

Let us know!

**Comment by iqxd** [comment] 2023-05-17 02:40
@dalthviz yes, I upgraded pyside6 to 6.5, and there seems no leak any more, thanks!

**Comment by dalthviz** [comment] 2023-11-23 21:23
Closing since seems like upgrading to PySide6 6.5.0 stopped the memory leak

**Closed by dalthviz** 2023-11-23 21:23 UTC
Labels: type:Bug, reso:notQtAwesome

**Comment by clint-enki** [comment] 2025-06-22 14:34
This is back starting from PySide 6.9.0

**Comment by adownsx64** [comment] 2025-10-21 13:06
Confirmed memory leak with `qta.Spin` (and still a memory leak with `qta.Pulse` but to a much lesser extent) in PySide 6.9.2. Had to downgrade to 6.8.3 to not have this issue.

**Comment by ccordoba12** [comment] 2025-10-21 16:26
PySide 6.9 is sort of semi-broken in our testing. So better to stick with 6.8 for the time being.
