### ISSUE TITLE
qta-browser "Empty key passed"

### ISSUE THREAD

**Issue by gravityfargo** [spyder-ide/qtawesome#231] opened 2023-03-26 05:03 UTC
When I run the command `qta-browser` I get the following error:

```
QSettings::value: Empty key passed
[1]    45198 segmentation fault (core dumped)  qta-browser
```

**Comment by dalthviz** [comment] 2023-03-29 20:41
Hi @gravityfargo thank you for the feedback! I was unable to reproduce this but could you give us more info about your setup (QtAwesome version you are using, OS, Python version, Qt version, way you installed QtAwesome, etc)?

Any new info in order to better understand what could be happening here is apreciated. Let us know!

**Comment by pedromorgan** [comment] 2023-05-04 23:00
so just hacked an update to the `qta-browser`
- at https://github.com/spyder-ide/qtawesome/pull/233
- and introduced qsettings..
- so this is spurious... or....

malware ?
https://www.google.com/search?channel=fs&client=ubuntu-sn&q=Empty+key+passed

**Comment by dalthviz** [comment] 2023-05-16 22:22
Hi @pedromorgan thank you for the feedback! So seems like this could not be related with QtAwesome but some other thing right? A good point there is that we don't use  `QSettings` in QtAwesome (at least not yet :) ). Maybe something faulty in the @gravityfargo qt installation or other qt based package could be causing such an error when launching the icon broswer?

**Comment by gravityfargo** [comment] 2023-07-20 04:42
Sorry for the delay. I haven't opened the app in a while, and when I just went to, I still get 
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
```
But there is no longer a seg fault.  I assume now that the crash was from a broken or misconfigured package. Are there any logs I could provide regarding this? This no longer crashes the app, so my issue is done, but if you'd like to explore the messages, I'm more than happy to provide any info.

**Comment by dalthviz** [comment] 2023-11-23 21:51
Thank you for the new info @gravityfargo and sorry for the late response too! I think there is not much we can do from the QtAwesome side of things. Since seems like you did nothing to your QtAwesome install but now no segfault is happening then indeed seems like the error coma from some sort of incompatibility between something in your setup and the QtAwesome install 🤔

Anyhow, since no segfault is happening I will be closing this for the moment. If you find out any other insights about the possible causes of the issue let us know!

**Closed by dalthviz** 2023-11-23 21:51 UTC
Labels: type:Bug, reso:notQtAwesome
